### ISSUE TITLE
Port should not be required config when DNS is specified

### ISSUE THREAD

**Issue by rprakashg-redhat** [fdo-rs/fido-device-onboard-rs#741]
Port should not be required when specifying DNS for owner addresses. Should be same in manufacturing server config file for RV info. In my demo environment in AWS all FDO servers are behind an ALB and shouldn't expect a port. Currently in my demo TO1 & TO2 flows from device are broken for this reason because Port is being added to request 

```yaml
---
ownership_voucher_store_driver:
  Directory:
    path: /etc/fdo/stores/owner_vouchers
session_store_driver:
  Directory:
    path: /etc/fdo/stores/owner_onboarding_sessions
trusted_device_keys_path: /etc/fdo/keys/device_ca_cert.pem
owner_private_key_path: /etc/fdo/keys/owner_key.der
owner_public_key_path: /etc/fdo/keys/owner_cert.pem
bind: "0.0.0.0:8081"
report_to_rendezvous_endpoint_enabled: true
service_info_api_url: "http://serviceinfo.sandbox2519.opentlc.com/device_info"
service_info_api_authentication:
  BearerToken:
    token: "Kpt5P/5flBkaiNSvDYS3cEdBQXJn2Zv9n1D50431/lo="
owner_addresses:
  - transport: http
    addresses:
      - dns_name: "owneronboarding.sandbox2519.opentlc.com"
    port: 8081
```
